# apiVersion: v2
# name: pgadmin-stack
# description: PostgreSQL  pgAdmin Stack
# type: application
# version: 0.1.0
# appVersion: "1.0"


apiVersion: v2
name: pg-stack
description: PostgreSQL  pgAdmin Stack
version: 0.1.0
type: application

dependencies:
  - name: pgadmin
    version: 0.1.0
    repository: "file://charts/pgadmin"
    condition: pgadmin.enabled
  - name: postgresql
    version: 0.1.0
    repository: "file://charts/postgresql"
    condition: postgresql.enabled
  - name: storageclass
    version: 0.1.0
    repository: "file://charts/storageclass"
    condition: storageclass.enabled
